Update api-management-service.md
Azure/API-Management pull request #39
Opened 2023-09-28 18:06 UTC by TCP1231

2023-09-28 18:27 UTC, vladvino commented on changelogs/api-management-service.md
> +1. We have introduced new Azure Advisor recommendations
Should there be ":" at the end of this line?

2023-09-28 18:28 UTC, vladvino commented on changelogs/api-management-service.md
> +2. We have fixed an issue where the OpenApi would fail if the parameter names where empty.
Please spell OpenAPI with API in all caps.

2023-09-28 18:29 UTC, vladvino commented on changelogs/api-management-service.md
> +6. Deleting API release will now return 204 instead of 404 if release does not exist.
Please replace "Deleting" with "We have deleted", assuming we've already done it.

2023-09-28 18:29 UTC, vladvino commented on changelogs/api-management-service.md
> +7. Removing support for the [retired set-graphql-resolver policy](https://learn.microsoft.com/en-us/azure/api-management/set-graphql-resolver-policy) which had already been replaced with GraphQL API
Please replace "Removed" with "We have removed", assuming we've already done it.

2023-09-28 18:29 UTC, vladvino commented on changelogs/api-management-service.md
> +## Release - API Management service: September 2023
Please group all fixes together.

2023-09-28 18:30 UTC, vladvino requested changes
Please see my comments. Thanks!

2023-09-29 00:14 UTC, TCP1231 reviewed
Made requested changes.

2023-09-29 00:25 UTC, vladvino approved these changes

2023-09-29 00:26 UTC, merged