Create Release40update
Azure/API-Management pull request #43
Opened 2023-10-19 22:33 UTC by TCP1231

2023-10-19 23:07 UTC, TCP1231 reviewed
updated as discussed

2023-10-19 23:17 UTC, vladvino approved these changes
Thank you!

2023-10-20 00:33 UTC, simonkurtz-MSFT commented on Release40update
> +- You can now specify timeout in milliseconds in the the `forward-request` policy via the new `timeout-ms` attribute.
@vladvino, double `the` here

2023-10-20 00:35 UTC, simonkurtz-MSFT commented on Release40update
> +- We fixed an issue where the `emit-metric` policy could fail the request when no diagnostic entries are configured at any of the scopes.
@vladvino, I believe 
`when no diagnostic entries are configured`
should be
`when no diagnostic entries were configured` 
as this is no longer an issue now after the fix.

2023-10-20 00:35 UTC, simonkurtz-MSFT commented on Release40update
> +- We fixed an issue where a request to a GraphQL API with empty GraphQL resolver policy fails the request.
@vladvino, I believe `fails` should be `failed` as the issue has been fixed.

2023-10-20 06:51 UTC, tomkerkhove requested changes
Added a request to remove and believe we should make these changes in https://github.com/Azure/API-Management/blob/main/changelogs/api-management-service.md instead

2023-10-20 06:51 UTC, tomkerkhove commented on Release40update
> +- We changed `validate-jwt` policy to properly handle `Bearer` and other authorization token schemas correctly in custom headers.
We should remove this, I deliberately did not share this as  there was a regression =)

Can you please remove this?

2023-11-08 21:33 UTC, closed without merging