0.45 release notes
Azure/API-Management pull request #55
Opened 2024-06-25 22:00 UTC by vladvino

2024-06-25 22:08 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- We added support for decryption keys to the [`validate-azure-ad-token`](https://learn.microsoft.com/azure/api-management/validate-jwt-policy) policy
The correct link is https://learn.microsoft.com/azure/api-management/validate-azure-ad-token-policy

2024-06-25 22:08 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- [`azure-openai-semantic-cache-lookup`](https://learn.microsoft.com/azure/api-management/azure-openai-semantic-cache-lookup-policy) and [`azure-openai-semantic-cache-store`](https://learn.microsoft.
Unnecessary full stop at the end

2024-06-25 22:12 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- We fixed a bug that caused XML entities to be erroneously unescaped in the policy documents
1. Not XML entities, but text values of XML elements.
2. Decoded, not unescaped.

2024-06-26 03:20 UTC, simonkurtz-MSFT commented on changelogs/api-management-service.md
> +- We've imprioved promt token estimation accuracy for GPT-4 models in the [`azure-openai-token-limit `](https://learn.microsoft.com/azure/api-management/azure-openai-token-limit-policy) policy
Typos on _improved_ and _prompt_

2024-06-26 03:22 UTC, simonkurtz-MSFT requested changes

2024-06-26 03:22 UTC, simonkurtz-MSFT commented on changelogs/api-management-service.md
> +- We fixed an issue which caused GraphQL resolver runtime errors when primitive type fileds had null value
Typo on _fields_

2024-06-26 03:22 UTC, simonkurtz-MSFT commented on changelogs/api-management-service.md
> +- Expressions are now work as expected for in the `<audience/>` elements in the [`validate-jwt`](https://learn.microsoft.com/azure/api-management/validate-jwt-policy) policy
Change to _Expressions now work as expected in the `<audience/>` elements ..._

2024-06-26 21:05 UTC, merged

2024-06-26 23:24 UTC, ferantoMSFT commented on changelogs/api-management-service.md
> +- Now customers can use Azure portal to [migrate](https://learn.microsoft.com/azure/api-management/migrate-stv1-to-stv2-vnet?#trigger-migration-of-a-network-injected-api-management-instance) their st
@vladvino please let's change "their stv1 service instances to stv2" to "their VNet injected stv1 service instances to stv2"... emphasis on VNet Injected.