Added notes for 0.47
Azure/API-Management pull request #60
Opened 2024-10-31 20:18 UTC by vladvino

2024-10-31 21:39 UTC, dlepow reviewed
@vladvino - Noted a couple typos.

2024-10-31 21:39 UTC, dlepow commented on changelogs/api-management-service.md
> +- [Azure OpenAI token limit policy](https://learn.microsoft.com/azure/api-management/azure-openai-token-limit-policy) now fully supports promts that include image.
```suggestion
- [Azure OpenAI token limit policy](https://learn.microsoft.com/azure/api-management/azure-openai-token-limit-policy) now fully supports prompts that include image.
```

2024-10-31 21:39 UTC, dlepow commented on changelogs/api-management-service.md
> +- [Validate Entra ID token policy](https://learn.microsoft.com/azure/api-management/validate-azure-ad-token-policy) now works with protected forwarde tokens (PFT) tokens.
```suggestion
- [Validate Entra ID token policy](https://learn.microsoft.com/azure/api-management/validate-azure-ad-token-policy) now works with protected forwarded tokens.
```

2024-11-01 15:04 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- You can now successfully add a workspace to a service configured with a custom host name.
1. Hostname, not host name
2. Specifically management API hostname
3. This is a bugfix, not a new feature

2024-11-01 15:06 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- Requests to an API in an [open product](https://learn.microsoft.com/azure/api-management/api-management-howto-add-products?tabs=azure-portal&pivots=interactive#access-to-product-apis) and containin
Should we announce it as a change, like we did in the previous release notes?

2024-11-01 15:06 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- [Validate content policy](https://learn.microsoft.com/azure/api-management/validate-content-policy) now works correctly with nullable properties in JSON payloads, including those defined by the `on
1. `oneOf`, not `onOf`
2. Can we explain what the behavior is?

2024-11-01 15:09 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +- [Validate Entra ID token policy](https://learn.microsoft.com/azure/api-management/validate-azure-ad-token-policy) now correctly puts unencrypted token into the context variable specified in the `ou
1. unencrypted -> decrypted
2. The policy is validate-azure-ad-token, not validate Entra ID token. Can we use the actual name or optionally both names for clarity?

2024-11-01 15:09 UTC, mikebudzynski commented on changelogs/api-management-service.md
> +
Extra new line to be removed

2024-11-01 15:46 UTC, nimakamoosi commented on changelogs/api-management-service.md
> +- [Azure OpenAI token limit policy](https://learn.microsoft.com/azure/api-management/azure-openai-token-limit-policy) now fully supports promts that include image.
promts -> prompts

2024-11-01 15:47 UTC, nimakamoosi commented on changelogs/api-management-service.md
> +
Shouldn't we mention GPT4o support along with image?

2024-11-01 16:44 UTC, simonkurtz-MSFT requested changes

2024-11-01 16:44 UTC, simonkurtz-MSFT commented on changelogs/api-management-service.md
> +- [Validate content policy](https://learn.microsoft.com/azure/api-management/validate-content-policy) now works correctly with nullable properties in JSON payloads, including those defined by the `on
Change `onOf` to `oneOf`.

2024-11-01 16:44 UTC, simonkurtz-MSFT commented on changelogs/api-management-service.md
> +- [Redirect content URLs policy](https://learn.microsoft.com/azure/api-management/redirect-content-urls-policy) doesn't add redundant slashes to the output URLs unlike it used to in some cases.
I think you meant _like it used to_.

2024-11-01 16:47 UTC, simonkurtz-MSFT approved these changes
I see that the two items I commented on have been resolved by Vlad now. Thank you!

2025-01-27 21:56 UTC, merged